name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.anandnanwana14 }}
          password: ${{ secrets.dckr_pat_bVSK0TFmfRZVMLk8U1VelBwXy-I }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.anandnanwana14 }}/node-app:latest ./node-backend
          docker push ${{ secrets.anandnanwana14 }}/node-app:latest
